version: '3.9'
services:
  nginx:
    platform: linux/amd64
    image: cr.selcloud.ru/cosmeticfrontend/nginx_container:latest
    container_name: nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nuxt
    volumes:
        - /etc/letsencrypt/live/cosmetic.yanco.ru/:/etc/letsencrypt/live/cosmetic.yanco.ru/
        - /etc/letsencrypt/:/etc/letsencrypt

  nuxt:
    platform: linux/amd64
    image: cr.selcloud.ru/cosmeticfrontend/nuxt_container:latest
    container_name: nuxt
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '3000:3000'
    restart: always